package com.saver.igv1.utils.Constants

object SettingsConstants {
    const val VIBRATION = "VIBRATION"
    const val STORY_EFFECT = "STORY_EFFECT"
    const val OFFLINE_EFFECT = "OFFLINE_EFFECT"
    const val USERWISE_MODE = "USERWISE_MODE"
    const val USER_NAME = "USER_NAME"
    const val APP_OPENED_TIME = "APP_OPENED_TIME"
    const val THEME = "THEME"
    const val LIVE_STORIES_OFFLINE_STATUS = "LIVE_STORIES_OFFLINE_STATUS"
    const val LIVE_STORIES_HOST_INFO = "LIVE_STORIES_HOST_INFO"
    const val SEEN_FIRST_TIME_OPEN = "SEEN_FIRST_TIME_OPEN"
    const val RATING_GIVEN = "RATING_GIVEN"
    const val RATING_DIALOG_NOTSHOW_AGAIN = "RATING_DIALOG_NOTSHOW_AGAIN"
    const val RATING_DIALOG_NOT_NOW = "RATING_DIALOG_NOT_NOW"
    const val RATING_DIALOG_NOT_NOW_TIME = "RATING_DIALOG_NOT_NOW_TIME"
    const val RATING_SHOW_NEVER_BOX = "RATING_SHOW_NEVER_BOX"
    const val DISABLE_ADS_PROMO = "DISABLE_ADS_PROMO"
    const val SHOW_ADS_PROMO = "SHOW_ADS_PROMO"
    const val IS_USER_CHANGED_HOMESCREEN = "IS_USER_CHANGED_HOMESCREEN"
    const val HIGHLIGHT_UNSEEN_LIVE_STORIES_ENABLE = "HIGHLIGHT_UNSEEN_LIVE_STORIES_ENABLE"
    const val DEFAULT_HOME_SCREEN = "Defaulthomescreen"
    ////////////

    const val AUTODOWNLOAD_EFFECT = "AUTODOWNLOAD_EFFECT"
    const val AUTODOWNLOAD_USERWISE_STORY_PLAYER_FLOW = "AUTODOWNLOAD_USERWISE_STORY_PLAYER_FLOW"
    const val FAV_STORY_MODE = "FAV_STORY_MODE"
    const val FAV_USER_MODE = "FAV_USER_MODE"
    const val DEFAULT_DOWNLOADING_OPTION = "DEFAULT_DOWNLOADING_OPTION"
}
