package com.saver.igv1.utils.Constants

object WorkManagerConstants {
    const val WORKER_DRIVE_FAV_STORIES_UPDATE_NOTIFICATION_ID = 9955
    const val WORKER_PHONE_FAV_ALLSTORIES_UPDATE_NOTIFICATION_ID = 7955
    const val WORKER_DRIVE_FAV_USERS_UPDATE_NOTIFICATION_ID = 6955
    const val WORKER_DRIVE_DELETE_STORIES_UPDATE_NOTIFICATION_ID = 9855
}