package com.cc.referral.utils.Constants

object ServiceConstants {
    const val SERVICE_NOTIFICATION_ID = 2029
    const val START_MULTIPLE_SERVICE = "START_MULTIPLE_SERVICE"
    const val UPDATE_MULTIPLE_SERVICE = "UPDATE_MULTIPLE_SERVICE"
    const val START_REELS_MULTIPLE_SERVICE = "START_REELS_MULTIPLE_SERVICE"
    const val UPDATE_REELS_MULTIPLE_SERVICE = "UPDATE_REELS_MULTIPLE_SERVICE"
    const val START_STORY_MULTIPLE_SERVICE = "START_STORY_MULTIPLE_SERVICE"
    const val UPDATE_STORY_MULTIPLE_SERVICE = "UPDATE_STORY_MULTIPLE_SERVICE"
    const val START_MULTIPLE_HIGHLIGHT_SERVICE = "START_MULTIPLE_HIGHLIGHT_SERVICE"
    const val UPDATE_MULTIPLE_HIGHLIGHT_SERVICE = "UPDATE_MULTIPLE_HIGHLIGHT_SERVICE"
    const val SERVICE_Media_NOTIFICATION_ID = 2030
    const val LARGE_MEDIA_SIZE = 20



    const val DRIVE_SYNC = "DRIVE_SYNC"
    const val DRIVE_SYNC_ID = "4469"
    const val DRIVE_BULK_DOWNLOAD_ID = "4470"
    const val DRIVE_SYNC_COMPLETED_ID = "4489"
    const val START_DRIVE_SYNC_SERVICE = "START_DRIVE_SYNC_SERVICE"
    const val START_DRIVE_BULK_DOWNLOAD_SERVICE = "START_DRIVE_BULK_DOWNLOAD_SERVICE"
    const val UPDATE_DRIVE_BULK_DOWNLOAD_SERVICE = "UPDATE_DRIVE_BULK_DOWNLOAD_SERVICE"


}